# Generated by Django 3.2.9 on 2021-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_cadastro', models.DateField(auto_now=True)),
                ('codigo_01', models.CharField(max_length=10)),
                ('codigo_02', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_03', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
