# Generated by Django 3.2.9 on 2021-11-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
