# Generated by Django 3.2.9 on 2021-11-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
