# Generated by Django 3.2.9 on 2021-11-11 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20211111_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 11, 11, 17, 42, 7, 973257, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
